// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCliYrHnjfjeqPbr-G4_RuZiIYLqxa9Rgo',
    appId: '1:173339721301:web:b16c8ef3a72eca8c5d5edc',
    messagingSenderId: '173339721301',
    projectId: 'instagram-project-c9934',
    authDomain: 'instagram-project-c9934.firebaseapp.com',
    storageBucket: 'instagram-project-c9934.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJPkgCiqVqji3SwvkBQ7GDpknOe67h6I',
    appId: '1:173339721301:android:770ce932f7f268505d5edc',
    messagingSenderId: '173339721301',
    projectId: 'instagram-project-c9934',
    storageBucket: 'instagram-project-c9934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gdyEcqcDCstnRpj_PQu9OR8QV5heMh4',
    appId: '1:173339721301:ios:77618270113248e65d5edc',
    messagingSenderId: '173339721301',
    projectId: 'instagram-project-c9934',
    storageBucket: 'instagram-project-c9934.appspot.com',
    iosBundleId: 'com.example.instagramProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gdyEcqcDCstnRpj_PQu9OR8QV5heMh4',
    appId: '1:173339721301:ios:b3c2f43ba21a2b775d5edc',
    messagingSenderId: '173339721301',
    projectId: 'instagram-project-c9934',
    storageBucket: 'instagram-project-c9934.appspot.com',
    iosBundleId: 'com.example.instagramProject.RunnerTests',
  );
}
